version: '3.13'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  chat-api:
    build: .
    ports:
      - '3000:3000'
    
    environment:
      RABBITMQ_URI: 'amqp://user:password@rabbitmq:5672'
